# Generated by Django 6.0.6 on 2026-07-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='user',
            new_name='actor',
        ),
    ]
